name: skadi
description: Flutter utilities packages for custom widgets and utilities function.
version: 2.0.9

homepage: https://www.lynical.com
repository: https://github.com/lynical-software/skadi
issue_tracker: https://github.com/lynical-software/skadi/issues

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
